/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package facultyapplication.ui;

import facultyapplication.repository.department.DepartmentListRepository;
import facultyapplication.repository.department.DepartmentRepository;
import facultyapplication.repository.subject.SubjectListRepository;
import facultyapplication.repository.subject.SubjectRepository;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author korisnik
 */
public class MainForm extends javax.swing.JFrame {
    private DepartmentRepository departmentRepository;
    private SubjectRepository subjectRepository;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        departmentRepository = new DepartmentListRepository();
        subjectRepository = new SubjectListRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuDepartment = new javax.swing.JMenu();
        menuItemCrudDepartment = new javax.swing.JMenuItem();
        menuSubject = new javax.swing.JMenu();
        menuItemCrudSubject = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDepartment.setText("Department");

        menuItemCrudDepartment.setText("CRUD department");
        menuItemCrudDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrudDepartmentActionPerformed(evt);
            }
        });
        menuDepartment.add(menuItemCrudDepartment);

        jMenuBar1.add(menuDepartment);

        menuSubject.setText("Subject");

        menuItemCrudSubject.setText("CRUD subject");
        menuItemCrudSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrudSubjectActionPerformed(evt);
            }
        });
        menuSubject.add(menuItemCrudSubject);

        jMenuBar1.add(menuSubject);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCrudDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrudDepartmentActionPerformed
       //otvori fromu za rad sa Department/om
        JFrame departmentForm = new DepartmentForm(departmentRepository);
        departmentForm.setVisible(true);
    }//GEN-LAST:event_menuItemCrudDepartmentActionPerformed

    private void menuItemCrudSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrudSubjectActionPerformed
        JDialog subjectForm = new SubjectForm(this, true,subjectRepository,departmentRepository);
        subjectForm.setVisible(true);
    }//GEN-LAST:event_menuItemCrudSubjectActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDepartment;
    private javax.swing.JMenuItem menuItemCrudDepartment;
    private javax.swing.JMenuItem menuItemCrudSubject;
    private javax.swing.JMenu menuSubject;
    // End of variables declaration//GEN-END:variables
}
