/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package facultyapplication.ui;

import facultyapplication.domain.Department;
import facultyapplication.domain.Subject;
import facultyapplication.repository.department.DepartmentRepository;
import facultyapplication.repository.subject.SubjectRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author korisnik
 */
public class SubjectForm extends javax.swing.JDialog {

    private SubjectRepository subjectRepository;
    private DepartmentRepository departmentRepository;

    /**
     * Creates new form SubjectForm
     */
    public SubjectForm(java.awt.Frame parent, boolean modal,
            SubjectRepository subjectRepository, DepartmentRepository departmentRepository) {
        super(parent, modal);
        this.subjectRepository = subjectRepository;
        this.departmentRepository = departmentRepository;

        initComponents();
        fillComboDepartment();
        fillSubjectTable();
        pnlUpdateSubject.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSubjects = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubjects = new javax.swing.JTable();
        pnlNewSubject = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEspb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboDepartment = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblEspbError = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        pnlUpdateSubject = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNameUpdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEspbUpdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboDepartmentUpdate = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        lblNameError1 = new javax.swing.JLabel();
        lblEspbError1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Subject form...");

        pnlSubjects.setBorder(javax.swing.BorderFactory.createTitledBorder("Subjects:"));

        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ESPB", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSubjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSubjects);

        javax.swing.GroupLayout pnlSubjectsLayout = new javax.swing.GroupLayout(pnlSubjects);
        pnlSubjects.setLayout(pnlSubjectsLayout);
        pnlSubjectsLayout.setHorizontalGroup(
            pnlSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSubjectsLayout.setVerticalGroup(
            pnlSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );

        pnlNewSubject.setBorder(javax.swing.BorderFactory.createTitledBorder("New subject:"));

        jLabel1.setText("Name:");

        jLabel2.setText("ESPB:");

        jLabel3.setText("Department:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblEspbError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlNewSubjectLayout = new javax.swing.GroupLayout(pnlNewSubject);
        pnlNewSubject.setLayout(pnlNewSubjectLayout);
        pnlNewSubjectLayout.setHorizontalGroup(
            pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEspb)
                    .addComponent(txtName)
                    .addComponent(comboDepartment, 0, 356, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewSubjectLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(lblEspbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNewSubjectLayout.setVerticalGroup(
            pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(pnlNewSubjectLayout.createSequentialGroup()
                        .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspbError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtEspb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNewSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMessage.setForeground(new java.awt.Color(255, 0, 0));

        pnlUpdateSubject.setBorder(javax.swing.BorderFactory.createTitledBorder("Update subject:"));

        jLabel4.setText("Name:");

        txtNameUpdate.setEditable(false);

        jLabel5.setText("ESPB:");

        jLabel6.setText("Department:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblNameError1.setForeground(new java.awt.Color(255, 0, 0));

        lblEspbError1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlUpdateSubjectLayout = new javax.swing.GroupLayout(pnlUpdateSubject);
        pnlUpdateSubject.setLayout(pnlUpdateSubjectLayout);
        pnlUpdateSubjectLayout.setHorizontalGroup(
            pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEspbUpdate)
                    .addComponent(txtNameUpdate)
                    .addComponent(comboDepartmentUpdate, 0, 356, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateSubjectLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addComponent(lblEspbError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUpdateSubjectLayout.setVerticalGroup(
            pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateSubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate)
                    .addGroup(pnlUpdateSubjectLayout.createSequentialGroup()
                        .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameError1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtNameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspbError1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtEspbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(comboDepartmentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlNewSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlUpdateSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMessage)
                .addGap(8, 8, 8)
                .addComponent(pnlNewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pnlUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        lblNameError.setText("");
        lblEspbError.setText("");
        try {
            String name = txtName.getText().trim();
            if (name.isEmpty()) {
                lblNameError.setText("Morate uneti ime predmeta!");
                return;
            }

            try {
                int espb = Integer.parseInt(txtEspb.getText().trim());
                Department department = (Department) comboDepartment.getSelectedItem();

                Subject subject = new Subject(name, espb, department);
                subjectRepository.save(subject);
                fillSubjectTable();
                //osvezi tabelu....

            } catch (NumberFormatException nfe) {
                lblEspbError.setText("Niste uneli broj!");
            } catch (Exception ex) {
                lblMessage.setText(ex.getMessage());
            }

        } catch (Exception e) {
            System.out.println("Desila se greska: " + e.getMessage());
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String name = txtNameUpdate.getText();
            int espb = Integer.parseInt(txtEspbUpdate.getText().trim());
            Department department = (Department) comboDepartmentUpdate.getSelectedItem();
            
            Subject subject = new Subject(name, espb, department);
            subjectRepository.update(subject);
            
            fillSubjectTable();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubjectsMouseClicked
        pnlUpdateSubject.setVisible(true);
        int selectedRow = tblSubjects.getSelectedRow();

        if (selectedRow != -1) {
            String name = tblSubjects.getValueAt(selectedRow, 0).toString();
            int espb = Integer.parseInt(tblSubjects.getValueAt(selectedRow, 1).toString());
            Department department = (Department) tblSubjects.getValueAt(selectedRow, 2);

            txtNameUpdate.setText(name);
            txtEspbUpdate.setText(espb + "");
            comboDepartmentUpdate.setSelectedItem(department);
        }

    }//GEN-LAST:event_tblSubjectsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Object> comboDepartment;
    private javax.swing.JComboBox<Object> comboDepartmentUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEspbError;
    private javax.swing.JLabel lblEspbError1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblNameError1;
    private javax.swing.JPanel pnlNewSubject;
    private javax.swing.JPanel pnlSubjects;
    private javax.swing.JPanel pnlUpdateSubject;
    private javax.swing.JTable tblSubjects;
    private javax.swing.JTextField txtEspb;
    private javax.swing.JTextField txtEspbUpdate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameUpdate;
    // End of variables declaration//GEN-END:variables

    private void fillComboDepartment() {
        //popuni kombobox sa podacima
        List<Department> departments = departmentRepository.getAll();
        for (Department department : departments) {
            // comboDepartment.addItem(department.getName() + "(" + department.getShortname() +")");
            comboDepartment.addItem(department);
            comboDepartmentUpdate.addItem(department);
        }
    }

    private void fillSubjectTable() {
        //clearTableSubjects();
        List<Subject> subjects = subjectRepository.getAll();
        DefaultTableModel dtm = (DefaultTableModel) tblSubjects.getModel();
        dtm.setRowCount(0);

        for (Subject s : subjects) {
            Object[] rowData = new Object[3];
            rowData[0] = s.getName();
            rowData[1] = s.getEspb();
            rowData[2] = s.getDepartment();
            dtm.addRow(rowData);
        }

    }

    private void clearTableSubjects() {
        tblSubjects.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Name", "ESPB", "Department"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }
}
